# Generated by Django 4.2.6 on 2023-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название предмета')),
                ('image', models.ImageField(upload_to='contacts/', verbose_name='Логотип сети')),
            ],
        ),
        migrations.AlterField(
            model_name='objacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления предмета'),
        ),
        migrations.AlterField(
            model_name='objacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления информации'),
        ),
    ]
