# Generated by Django 4.2.5 on 2023-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_front', '0003_contacts_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(upload_to='contacts', verbose_name='Логотип сети'),
        ),
        migrations.AlterField(
            model_name='objacts',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Описание предмета'),
        ),
        migrations.AlterField(
            model_name='objacts',
            name='image',
            field=models.ImageField(default=None, upload_to='objacts_img', verbose_name='Изображение предмета'),
        ),
    ]
